alias da="docker attach"
alias dc="docker-compose"
alias dm="docker-machine"
alias dss="docker-sync start"
alias startosf="docker-compose up -d assets elasticsearch postgres tokumx mfr wb fakecas sharejs worker web api preprints"
alias stoposf="docker-compose down"
alias dclogs="docker-compose logs -f --tail 100 "
