
- name: Uninstall brew-installed autoenv if necessary
  homebrew: name=autoenv state=present
  when: ansible_os_family == "Darwin"

# Use git install autoenv for best cross-platform compatibility
- name: Clone autoenv
  git:
    repo: https://github.com/kennethreitz/autoenv.git
    dest: "{{ '~/.autoenv' | expanduser}}"
    update: no
  when: ansible_os_family != "Darwin"
